# Generated by Django 5.2.2 on 2025-06-13 17:13

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('picture', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='описание')),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('picture', models.ImageField(upload_to='', verbose_name='картинка')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('picture', models.ImageField(upload_to='', verbose_name='картинка')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('picture', models.ImageField(upload_to='', verbose_name='картинка')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('picture', models.ImageField(upload_to='', verbose_name='картинка')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MerchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('picture', models.ImageField(upload_to='', verbose_name='картинка')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('M', 'Передан менеджеру'), ('R', 'Передан ресторану'), ('C', 'Передан курьеру'), ('P', 'Обработанный')], db_index=True, default='M', max_length=1, verbose_name='Статус')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Зарегистрирован в')),
                ('called_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Позвонили в')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доставлен в')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена заказа')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('C', 'Наличные'), ('N', 'Безналичные')], db_index=True, default='C', max_length=1, verbose_name='Способ оплаты')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField()),
            ],
        ),
    ]
