# Generated by Django 5.2.2 on 2025-06-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(default=None, upload_to='', verbose_name='картинка'),
        ),
    ]
