# Generated by Django 5.2.2 on 2025-07-04 17:15

import uuid
from django.db import migrations, models
from django.db.migrations import RunPython


def make_unique_uuid(apps, schema_editor):
    Food = apps.get_model('area', 'Food')
    Merch = apps.get_model('area', 'Merch')
    for Model in (Food, Merch):
        for product in Model.objects.all():
            product.uuid = uuid.uuid4()
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('area', '0004_food_uuid_merch_uuid'),
    ]

    operations = [
        RunPython(make_unique_uuid),
        migrations.AlterField(
            model_name='food',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

    ]
