# Generated by Django 5.2.2 on 2025-07-07 08:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0005_alter_food_uuid_alter_merch_uuid'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Anime', 'verbose_name_plural': 'Animes'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderelement',
            options={'verbose_name': 'Order Element', 'verbose_name_plural': 'Order Elements'},
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.anime', verbose_name='Anime'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(default=None, upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='food',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.anime', verbose_name='Anime'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='area.foodcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='area.foodingredient', verbose_name='Food Ingredient'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='food',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Uuid'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='foodingredient',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodingredient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='foodingredient',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to='area.anime', verbose_name='Anime'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='merch_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.merchcategory', verbose_name='Merch Category'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='merchcategory',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='merchcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='merchcategory',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name='Delivery address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Called at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Delivered at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('M', 'Transferred to manager'), ('R', 'Transferred to the restaurant'), ('C', 'Handed over to the courier'), ('P', 'Processed')], db_index=True, default='M', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='area.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('C', 'Cash'), ('N', 'Noncash')], db_index=True, default='C', max_length=1, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='area.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(verbose_name='Paid at'),
        ),
    ]
