# Generated by Django 5.2.2 on 2025-07-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0006_alter_anime_options_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Is Draft'),
        ),
    ]
