# Generated by Django 5.2.2 on 2025-08-03 15:41

from django.db import migrations


def migrate_products(apps, schema_editor):
    Food = apps.get_model('area', 'Food')
    Merch = apps.get_model('area', 'Merch')
    FoodCategory = apps.get_model('area', 'FoodCategory')
    MerchCategory = apps.get_model('area', 'MerchCategory')
    FoodIngredient = apps.get_model('area', 'FoodIngredient')
    Product = apps.get_model('area', 'Product')
    ProductCategory = apps.get_model('area', 'ProductCategory')
    ProductIngredient = apps.get_model('area', 'ProductIngredient')

    category_map = {}
    for cat in FoodCategory.objects.all():
        new_cat = ProductCategory.objects.update_or_create(
            name=cat.name,
            picture=cat.picture,
            description=cat.description
        )
        category_map[f'food_{cat.id}'] = new_cat

    for cat in MerchCategory.objects.all():
        new_cat = ProductCategory.objects.update_or_create(
            name=cat.name,
            picture=cat.picture,
            description=cat.description
        )
        category_map[f'merch_{cat.id}'] = new_cat

    ingredient_map = {}
    for ing in FoodIngredient.objects.all():
        new_ing = ProductIngredient.objects.create(
            name=ing.name,
            picture=ing.picture,
            description=ing.description
        )
        ingredient_map[ing.id] = new_ing

    for f in Food.objects.all():
        Product.objects.create(
            uuid=f.uuid,
            name=f.name,
            anime=f.anime,
            product_category=ProductCategory.objects.get(id=1),
            price=f.price,
            picture=f.picture,
            description=f.description,
            product_ingredient=ingredient_map.get(f.food_ingredient_id),
            size=None,
        )

    for m in Merch.objects.all():
        Product.objects.create(
            uuid=m.uuid,
            name=m.name,
            anime=m.anime,
            product_category=ProductCategory.objects.get(id=1),
            price=m.price,
            picture=m.picture,
            description=m.description,
            product_ingredient=None,
            size=m.size,
        )

class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('area', '0008_productcategory_productingredient_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_products)
    ]
