# Generated by Django 5.2.2 on 2025-08-08 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0009_auto_20250803_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderelement',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orderelement',
            name='object_id',
        ),
        migrations.AddField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='area.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='area.producttype', verbose_name='Product Type'),
        ),
    ]
