# Generated by Django 5.2.2 on 2025-08-15 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0010_producttype_remove_orderelement_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_ingredient',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='anime',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='merch_category',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_categories', to='area.productcategory', verbose_name='Product Category'),
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodIngredient',
        ),
        migrations.DeleteModel(
            name='Merch',
        ),
        migrations.DeleteModel(
            name='MerchCategory',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
