# Generated by Django 5.2.2 on 2025-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
