# Generated by Django 5.2.2 on 2025-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_email_verifed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to='user_pictures', verbose_name='Picture'),
        ),
    ]
