# Generated by Django 5.2.2 on 2025-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='user_pictures/default.png', upload_to='user_pictures', verbose_name='Picture'),
        ),
    ]
